title: Schema4PaN
description: Developing a metadata schema for datasets from Photon and Neutron (PaN) experiments, for and together with the community. 
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
